sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.7"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - npm lix use haxe $TRAVIS_HAXE_VERSION
  - npm run haxe build-js.hxml
  - npm run haxe build-nodejs.hxml
  - npm run haxe build-python.hxml
  - npm run haxe build-swf.hxml
  - npm run haxe build-as3.hxml
  - npm run haxe build-lua.hxml
  - npm run haxe build-php7.hxml
  - npm run haxe build-neko.hxml
  - npm run haxe build-hl.hxml
  - npm run haxe build-php.hxml
  - npm run haxe build-java.hxml
  - npm run haxe build-cpp.hxml
  - npm run haxe build-cs.hxml


deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true